In [1]:
import pandas as pd
import sqlite3

In [2]:
import pandas as pd
import sqlite3

df = pd.read_csv(r"C:\Users\TejaswiniD\Downloads\archive (3)\sales.csv")

conn = sqlite3.connect("sales.db")

df.to_sql("sales", conn, if_exists="replace", index=False)

print("Database Created Successfully")

Database Created Successfully

In [3]:
query = "SELECT * FROM sales LIMIT 10"

result = pd.read_sql(query, conn)

result

,Area Code,State,Market,Market Size,Profit,Margin,Sales,COGS,Total Expenses,Marketing,Inventory,Budget Profit,Budget COGS,Budget Margin,Budget Sales,ProductId,Date,Product Type,Product,Type
0,203,Connecticut,East,Small Market,107.0,176.0,292.0,116.0,69.0,38.0,962.0,110.0,110.0,160.0,270.0,2,04/01/10 00:00:00,Coffee,Columbian,Regular
1,203,Connecticut,East,Small Market,75.0,135.0,225.0,90.0,60.0,29.0,1148.0,90.0,80.0,130.0,210.0,2,07/01/10 00:00:00,Coffee,Columbian,Regular
2,203,Connecticut,East,Small Market,122.0,195.0,325.0,130.0,73.0,42.0,1134.0,130.0,110.0,180.0,290.0,2,11/01/10 00:00:00,Coffee,Columbian,Regular
3,203,Connecticut,East,Small Market,105.0,174.0,289.0,115.0,69.0,37.0,1166.0,110.0,100.0,160.0,260.0,2,12/01/10 00:00:00,Coffee,Columbian,Regular
4,203,Connecticut,East,Small Market,104.0,135.0,223.0,90.0,56.0,29.0,1148.0,90.0,80.0,130.0,210.0,2,07/01/11 00:00:00,Coffee,Columbian,Regular
5,203,Connecticut,East,Small Market,104.0,135.0,223.0,90.0,56.0,29.0,1139.0,90.0,80.0,130.0,210.0,2,08/01/11 00:00:00,Coffee,Columbian,Regular
6,203,Connecticut,East,Small Market,135.0,155.0,275.0,103.0,64.0,33.0,1130.0,110.0,90.0,150.0,240.0,2,09/01/11 00:00:00,Coffee,Columbian,Regular
7,203,Connecticut,East,Small Market,171.0,188.0,334.0,125.0,73.0,41.0,1119.0,130.0,100.0,160.0,260.0,2,10/01/11 00:00:00,Coffee,Columbian,Regular
8,203,Connecticut,East,Small Market,181.0,195.0,346.0,130.0,73.0,42.0,1134.0,130.0,110.0,180.0,290.0,2,11/01/11 00:00:00,Coffee,Columbian,Regular
9,203,Connecticut,East,Small Market,15.0,31.0,51.0,20.0,16.0,5.0,804.0,20.0,20.0,30.0,50.0,13,06/01/10 00:00:00,Tea,Green Tea,Regular

In [4]:
query = """
SELECT *
FROM sales
WHERE Profit > 100
"""

pd.read_sql(query, conn)

,Area Code,State,Market,Market Size,Profit,Margin,Sales,COGS,Total Expenses,Marketing,Inventory,Budget Profit,Budget COGS,Budget Margin,Budget Sales,ProductId,Date,Product Type,Product,Type
0,203,Connecticut,East,Small Market,107.0,176.0,292.0,116.0,69.0,38.0,962.0,110.0,110.0,160.0,270.0,2,04/01/10 00:00:00,Coffee,Columbian,Regular
1,203,Connecticut,East,Small Market,122.0,195.0,325.0,130.0,73.0,42.0,1134.0,130.0,110.0,180.0,290.0,2,11/01/10 00:00:00,Coffee,Columbian,Regular
2,203,Connecticut,East,Small Market,105.0,174.0,289.0,115.0,69.0,37.0,1166.0,110.0,100.0,160.0,260.0,2,12/01/10 00:00:00,Coffee,Columbian,Regular
3,203,Connecticut,East,Small Market,104.0,135.0,223.0,90.0,56.0,29.0,1148.0,90.0,80.0,130.0,210.0,2,07/01/11 00:00:00,Coffee,Columbian,Regular
4,203,Connecticut,East,Small Market,104.0,135.0,223.0,90.0,56.0,29.0,1139.0,90.0,80.0,130.0,210.0,2,08/01/11 00:00:00,Coffee,Columbian,Regular
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
962,978,Massachusetts,East,Major Market,778.0,613.0,659.0,52.0,46.0,17.0,-1493.0,560.0,40.0,590.0,630.0,2,07/01/11 00:00:00,Coffee,Columbian,Regular
963,979,Texas,South,Major Market,250.0,367.0,678.0,311.0,117.0,96.0,1296.0,340.0,390.0,450.0,840.0,2,08/01/10 00:00:00,Coffee,Columbian,Regular
964,979,Texas,South,Major Market,155.0,152.0,254.0,104.0,37.0,29.0,952.0,120.0,80.0,140.0,220.0,5,07/01/11 00:00:00,Espresso,Caffe Mocha,Regular
965,985,Louisiana,South,Small Market,126.0,130.0,246.0,101.0,45.0,33.0,552.0,80.0,90.0,120.0,210.0,8,11/01/11 00:00:00,Herbal Tea,Chamomile,Decaf
966,985,Louisiana,South,Small Market,114.0,120.0,228.0,94.0,43.0,31.0,540.0,70.0,80.0,110.0,190.0,8,12/01/11 00:00:00,Herbal Tea,Chamomile,Decaf

In [5]:
query = """
SELECT *
FROM sales
ORDER BY Sales DESC
"""

pd.read_sql(query, conn)

,Area Code,State,Market,Market Size,Profit,Margin,Sales,COGS,Total Expenses,Marketing,Inventory,Budget Profit,Budget COGS,Budget Margin,Budget Sales,ProductId,Date,Product Type,Product,Type
0,707,California,West,Major Market,370.0,548.0,912.0,364.0,178.0,127.0,2654.0,530.0,450.0,690.0,1140.0,2,07/01/10 00:00:00,Coffee,Columbian,Regular
1,845,New York,East,Major Market,370.0,548.0,912.0,364.0,178.0,127.0,2654.0,370.0,340.0,520.0,860.0,2,07/01/10 00:00:00,Coffee,Columbian,Regular
2,650,California,West,Major Market,368.0,546.0,910.0,364.0,178.0,127.0,2617.0,520.0,450.0,680.0,1130.0,2,08/01/10 00:00:00,Coffee,Columbian,Regular
3,845,New York,East,Major Market,368.0,546.0,910.0,364.0,178.0,127.0,2617.0,370.0,340.0,520.0,860.0,2,08/01/10 00:00:00,Coffee,Columbian,Regular
4,650,California,West,Major Market,511.0,548.0,904.0,364.0,166.0,127.0,2654.0,530.0,450.0,690.0,1140.0,2,07/01/11 00:00:00,Coffee,Columbian,Regular
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4243,775,Nevada,West,Small Market,-430.0,-302.0,19.0,302.0,147.0,114.0,6413.0,-280.0,190.0,-190.0,0.0,13,09/01/10 00:00:00,Tea,Green Tea,Regular
4244,775,Nevada,West,Small Market,-552.0,-245.0,19.0,245.0,132.0,93.0,1419.0,-240.0,160.0,-160.0,0.0,13,01/01/11 00:00:00,Tea,Green Tea,Regular
4245,702,Nevada,West,Small Market,-380.0,-265.0,18.0,265.0,133.0,100.0,3742.0,-250.0,170.0,-170.0,0.0,13,05/01/10 00:00:00,Tea,Green Tea,Regular
4246,702,Nevada,West,Small Market,-524.0,-265.0,18.0,265.0,124.0,100.0,3742.0,-250.0,170.0,-170.0,0.0,13,05/01/11 00:00:00,Tea,Green Tea,Regular
4247,702,Nevada,West,Small Market,-354.0,-245.0,17.0,245.0,126.0,93.0,1419.0,-240.0,160.0,-160.0,0.0,13,01/01/10 00:00:00,Tea,Green Tea,Regular

In [6]:
query = """
SELECT *
FROM sales
ORDER BY Sales DESC
"""

pd.read_sql(query, conn)

,Area Code,State,Market,Market Size,Profit,Margin,Sales,COGS,Total Expenses,Marketing,Inventory,Budget Profit,Budget COGS,Budget Margin,Budget Sales,ProductId,Date,Product Type,Product,Type
0,707,California,West,Major Market,370.0,548.0,912.0,364.0,178.0,127.0,2654.0,530.0,450.0,690.0,1140.0,2,07/01/10 00:00:00,Coffee,Columbian,Regular
1,845,New York,East,Major Market,370.0,548.0,912.0,364.0,178.0,127.0,2654.0,370.0,340.0,520.0,860.0,2,07/01/10 00:00:00,Coffee,Columbian,Regular
2,650,California,West,Major Market,368.0,546.0,910.0,364.0,178.0,127.0,2617.0,520.0,450.0,680.0,1130.0,2,08/01/10 00:00:00,Coffee,Columbian,Regular
3,845,New York,East,Major Market,368.0,546.0,910.0,364.0,178.0,127.0,2617.0,370.0,340.0,520.0,860.0,2,08/01/10 00:00:00,Coffee,Columbian,Regular
4,650,California,West,Major Market,511.0,548.0,904.0,364.0,166.0,127.0,2654.0,530.0,450.0,690.0,1140.0,2,07/01/11 00:00:00,Coffee,Columbian,Regular
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4243,775,Nevada,West,Small Market,-430.0,-302.0,19.0,302.0,147.0,114.0,6413.0,-280.0,190.0,-190.0,0.0,13,09/01/10 00:00:00,Tea,Green Tea,Regular
4244,775,Nevada,West,Small Market,-552.0,-245.0,19.0,245.0,132.0,93.0,1419.0,-240.0,160.0,-160.0,0.0,13,01/01/11 00:00:00,Tea,Green Tea,Regular
4245,702,Nevada,West,Small Market,-380.0,-265.0,18.0,265.0,133.0,100.0,3742.0,-250.0,170.0,-170.0,0.0,13,05/01/10 00:00:00,Tea,Green Tea,Regular
4246,702,Nevada,West,Small Market,-524.0,-265.0,18.0,265.0,124.0,100.0,3742.0,-250.0,170.0,-170.0,0.0,13,05/01/11 00:00:00,Tea,Green Tea,Regular
4247,702,Nevada,West,Small Market,-354.0,-245.0,17.0,245.0,126.0,93.0,1419.0,-240.0,160.0,-160.0,0.0,13,01/01/10 00:00:00,Tea,Green Tea,Regular

In [7]:
query = """
SELECT COUNT(*) AS Total_Records
FROM sales
"""

pd.read_sql(query, conn)

   Total_Records
0           4248

In [8]:
query = """
SELECT SUM(Sales) AS Total_Sales
FROM sales
"""

pd.read_sql(query, conn)

   Total_Sales
0     819811.0

In [9]:
query = """
SELECT AVG(Profit) AS Average_Profit
FROM sales
"""

pd.read_sql(query, conn)

   Average_Profit
0       61.097693

In [10]:
query = """
SELECT Market,
       SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Market
"""

pd.read_sql(query, conn)

    Market  Total_Sales
0  Central     265045.0
1     East     178576.0
2    South     103926.0
3     West     272264.0

In [11]:
query = """
SELECT [Product Type],
       AVG(Profit) AS Avg_Profit
FROM sales
GROUP BY [Product Type]
"""

pd.read_sql(query, conn)

  Product Type  Avg_Profit
0       Coffee   70.722538
1     Espresso   58.350340
2   Herbal Tea   59.899621
3          Tea   55.193750